### ISSUE TITLE
Error stage git_archive on macos

### ISSUE THREAD

**Issue by EgorLyutov** [flant/werf#1351]
Hello. 
Command tar -xf on git_archive stage fails with error:
/.dapp/deps/base/0.2.3/embedded/bin/tar: api/hotels/docs/docbook/build/lib/java: Directory renamed before its status could be extracted
/.dapp/deps/base/0.2.3/embedded/bin/tar: api/hotels/docs/docbook/build/lib: Directory renamed before its status could be extracted
/.dapp/deps/base/0.2.3/embedded/bin/tar: api/hotels/docs/docbook/build: Directory renamed before its status could be extracted
/.dapp/deps/base/0.2.3/embedded/bin/tar: api/hotels/docs/docbook: Directory renamed before its status could be extracted
/.dapp/deps/base/0.2.3/embedded/bin/tar: api/hotels/docs: Directory renamed before its status could be extracted
/.dapp/deps/base/0.2.3/embedded/bin/tar: api/hotels: Directory renamed before its status could be extracted
/.dapp/deps/base/0.2.3/embedded/bin/tar: api: Directory renamed before its status could be extracted
/.dapp/deps/base/0.2.3/embedded/bin/tar: Exiting with failure status due to previous errors

**Comment by alexey-igrychev** [comment]
solved
