### ISSUE TITLE
git version parsing error on macOS

### ISSUE THREAD

**Issue by zamai** [flant/werf#1429]
`werf build --stages-storage :local`

fails with error:
```
Error: unexpected `git --version` output:
git version 2.17.2 (Apple Git-113)
Git version >= 1.9.0 required! To use submodules install git >= 2.14.0.
```
my macOS has:
```
$ git --version                                                                  
git version 2.17.2 (Apple Git-113)
```
Looking into source code I think [version parsing](https://github.com/flant/werf/blob/master/pkg/true_git/init.go#L91) should be adjusted to accommodate git versions like mine

**Comment by distorhead** [comment]
@zamai 

Hi! Try https://github.com/flant/werf/releases/tag/v1.0.0-beta.12
