### ISSUE TITLE
Multirep and monorep publish modes

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1500]
monorep:
* REPO:imageA-mytag
* REPO:imageB-mytag

multirep:
* REPO/imageA:mytag
* REPO/imageB:mytag

`--images-repo-mode` param (?).

**Comment by alexey-igrychev** [comment]
To separate the images with intersecting names (it is critical during the cleanup process), I propose the following format for monorep mode:
```
REPO:imageA--mytag
```
