### ISSUE TITLE
Doc typos and broken links

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1543]
1. Broken link to install dependencies.

![Screenshot from 2019-05-29 12-56-36](https://user-images.githubusercontent.com/1161992/58548218-90fc0080-8211-11e9-9e3d-a28d8c38e7de.png)

2. Typo `usermod -Ga` should be `usermod -aG` in gitlab howto: https://werf.io/documentation/guides/gitlab_ci_cd_integration.html#setup-runner

**Comment by distorhead** [comment]
Broken link "Other guides".
![Screenshot from 2019-06-03 13-47-47](https://user-images.githubusercontent.com/1161992/58796541-3e05bd00-8606-11e9-8074-6f68cffad588.png)

**Comment by distorhead** [comment]
404 when click on "Documentation" from this page:

![image](https://user-images.githubusercontent.com/1161992/59108165-fc954a80-8942-11e9-8d3c-b51247d00b7c.png)

**Comment by distorhead** [comment]
1.0.2-alpha.12 is awaiable, but not showed as actula version

![image](https://user-images.githubusercontent.com/1161992/59115481-0d998800-8952-11e9-8c8e-6da58e3e3800.png)

**Comment by alexey-igrychev** [comment]
solved
