### ISSUE TITLE
sha256sum: unrecognized option '--ignore-missing'

### ISSUE THREAD

**Issue by FessAectan** [flant/werf#1544]
A problem in the script get.sh on CentOS 7

https://werf.io/documentation/guides/gitlab_ci_cd_integration.html#setup-runner
step 8

```
curl -L https://raw.githubusercontent.com/flant/multiwerf/master/get.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2105  100  2105    0     0   5557      0 --:--:-- --:--:-- --:--:--  5568
Downloading multiwerf-linux-amd64-v1.0.13 from bintray...
sha256sum: unrecognized option '--ignore-missing'
Try 'sha256sum --help' for more information.
multiwerf-linux-amd64-v1.0.13 sha256 hash is not verified. Please download and check hash manually.
```

OS and sha256sum version:
sha256sum (GNU coreutils) 8.22
CentOS Linux release 7.6.1810 (Core)

**Comment by diafour** [comment]
Hello! Thank you for report. We've faced this earlier on Alpine. The workaround was to install sha256sum from another package.

Meanwhile, `get.sh` is now compatible with old sha256sum versions: https://github.com/flant/multiwerf/issues/30.
