### ISSUE TITLE
Werf output is broken in 12 gitlab

### ISSUE THREAD

**Issue by distorhead** [flant/werf#1698]
Excess newlines in werf output:

```
Publishing tag test-tag
 (1.79 seconds)

│

│

└

git-branch tagging strategy
 (1.79 seconds)

│

└

⛵ image myimage
 (1.86 seconds)

└

Publishing images
 (1.86 seconds)
```

Reproduces in the 12.1.4 gitlab version. Works in some 12 gitlab versions.

Maybe it is related to the following feature of 12 gitlab:

![image](https://user-images.githubusercontent.com/1161992/62611543-7b404100-b90e-11e9-8363-38c72e8d3110.png)

**Comment by distorhead** [comment]
Workaround: 

```
CI / CD Settings -> Variables: WERF_LOG_COLOR_MODE: off
```

Bug was introduced in the gitlab 12.1.4: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/31262#note_200663321

**Comment by alexey-igrychev** [comment]
fixed in https://about.gitlab.com/2019/08/22/gitlab-12-2-released/index.html
