### ISSUE TITLE
Support of RUN --mount flags

### ISSUE THREAD

**Issue by VolCh** [flant/werf#1767]
```
# syntax=docker/dockerfile:1.1.1-experimental
FROM php:7.2.21-fpm
COPY --from=composer:1.8.6 /usr/bin/composer /usr/bin/composer
COPY composer.json composer.lock ./
RUN --mount=type=ssh install --no-autoloader --no-scripts --no-interaction
```
cause `Error: Dockerfile parse error line 5: Unknown flag: mount` during `werf build`

As far as I understand Werf use BuildKit and should support all its features by default. But it seems like Werf parses `# syntax` directive https://docs.docker.com/engine/reference/builder/#syntax like a comment.

Is it a bug, an outdated version of moby/buildkit or an unsupported feature of BuildKit?

**Comment by distorhead** [comment]
Looks like werf parser of Dockerfile actually breaks on the last RUN directive (line 5). It is certainly a bug in werf.
