### ISSUE TITLE
werf helm secret does't work with custom editor

### ISSUE THREAD

**Issue by mfominov** [flant/werf#1869]
Trying to edit secret in vscode:
EDITOR="code --wait" werf helm secret file edit secret-values.yaml
result:
Error: exec: "code --wait": executable file not found in $PATH
expected result:
edit secrets in vscode

code --version
1.39.2
6ab598523be7a800d7f3eb4d92d7ab9a66069390
x64

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A583

**Comment by distorhead** [comment]
Workaround for now is to create script like that:

```
$ cat /usr/local/bin/mycode
exec code -r --wait $@
$ export EDITOR=mycode
```

**Comment by distorhead** [comment]
Also I forgot that werf already supports this EDITOR with arguments https://github.com/flant/werf/pull/1993.
