### ISSUE TITLE
Падает во время сборки на локальном компьютере

### ISSUE THREAD

**Issue by dgdagadin87** [flant/werf#2153]
Добрый день.

У меня такая проблема - пытаюсь сделать make build, на этапе beforeInstall выдается ошибка

<pre><b>Building stages</b>
<b>│</b> <font color="#34E2E2"><b>┌</b></font> <font color="#34E2E2"><b>🛸 artifact base</b></font>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <b>Use cache image for stage from</b>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <font color="#729FCF">    repository: werf-stages-storage/processing</font>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <font color="#729FCF">      image_id: a79ece4953bb</font>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <font color="#729FCF">       created: 2020-02-19T16:57:55.219984421Z</font>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <font color="#729FCF">           tag: 06bf6b4e0807da1cd6c03bbfdd97620e12f081f6898c38c41821c3b4814210ab</font>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <font color="#729FCF">          size: 61.2 MiB</font>
<b>│</b> <font color="#34E2E2"><b>│</b></font> 
<b>│</b> <font color="#34E2E2"><b>│</b></font> <b>┌</b> <b>Building stage beforeInstall</b>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <b>│</b> <font color="#34E2E2"><b>base/beforeInstall</b></font>  /.werf/stapel/embedded/bin/bash: /.werf/shell/script.sh: No such file or directory
<b>│</b> <font color="#34E2E2"><b>│</b></font> <b>├</b> <b>Info</b>
<b>│</b> <font color="#34E2E2"><b>│</b></font> <b>└</b> <font color="#EF2929"><b>Building stage beforeInstall (1.70 seconds) FAILED</b></font>
<b>│</b> <font color="#34E2E2"><b>└</b></font> <font color="#EF2929"><b>🛸 artifact base (1.70 seconds) FAILED</b></font>
<b>└</b> <font color="#EF2929"><b>Building stages (1.70 seconds) FAILED</b></font>
</pre>

Участок werf.yaml
<pre>
artifact: base
from: "ubuntu:18.04"

mount:
- from: build_dir
  to: /var/cache/apt
- from: tmp_dir
  to: /var/lib/apt/lists

shell:
  beforeInstall:
  - ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
  - apt-get -q update
  - apt-get -q install -y mc nano git curl wget gnupg2 iputils-ping net-tools ca-certificates software-properties-common
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -E -
  - apt-get -q install -y nodejs
</pre>

Очень буду признателен за помощь.

**Comment by distorhead** [comment]
Добрый день!

Проблема может быть связана с тем, что docker-сервер запущен на другом хосте или в виртуалке. Werf требует чтобы docker server был на том же хосте, т.к. используется монтирование директорий в сборочный контейнер. В данном случае с хоста где запущен werf в сборочный контейнер монтируется служебная директория `/.werf/shell` в которой должен быть подготовлен билд скрипт script.sh. Если запустить с другого хоста, то там будет пусто.

**Comment by alexey-igrychev** [comment]
Операционная система windows? 
Если да, то используется ли интеграция с WSL?

**Comment by dgdagadin87** [comment]
ОС Ubuntu

**Comment by dgdagadin87** [comment]
> Добрый день!
> 
> Проблема может быть связана с тем, что docker-сервер запущен на другом хосте или в виртуалке. Werf требует чтобы docker server был на том же хосте, т.к. используется монтирование директорий в сборочный контейнер. В данном случае с хоста где запущен werf в сборочный контейнер монтируется служебная директория `/.werf/shell` в которой должен быть подготовлен билд скрипт script.sh. Если запустить с другого хоста, то там будет пусто.

А как мне проверить на каком хосте запущен docker-server?
P.S. я новичок во всем что касается docker, kubernetes, werf, только второй день разбираюсь, поэтому прошу прощения за глупые вопросы.

**Comment by alexey-igrychev** [comment]
Вариант с remote Docker daemon отбрасываем, так как собралась стадия from.
Какая используется версия werf и docker (_docker version_)?

**Comment by dgdagadin87** [comment]
По werf:
<pre>v1.0.3-beta.9</pre>

По docker:
<pre>Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
</pre>

**Comment by alexey-igrychev** [comment]
А какой результат, если переопределить tmp директорию?

```
mkdir ~/werf_tmp
export WERF_TMP_DIR=~/werf_tmp
werf build -s=:local
```

**Comment by alexey-igrychev** [comment]
werf запускается не в контейнере и проблема не уходит при повторном запуске, так?

**Comment by distorhead** [comment]
> По werf:
> 
> v1.0.3-beta.9
> По docker:
> 
> Client: Docker Engine - Community
>  Version:           19.03.5
>  API version:       1.39 (downgraded from 1.40)
>  Go version:        go1.12.12
>  Git commit:        633a0ea838
>  Built:             Wed Nov 13 07:29:52 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server:
>  Engine:
>   Version:          18.09.9
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.13.4
>   Git commit:       9552f2b
>   Built:            Sat Nov 16 01:07:48 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false

Лучше использовать версию через `source <(multiwerf use 1.0 stable)`. 1.0.3 — это что-то старое.

**Comment by dgdagadin87** [comment]
> А какой результат, если переопределить tmp директорию?
> 
> ```
> mkdir ~/werf_tmp
> export WERF_TMP_DIR=~/werf_tmp
> werf build -s=:local
> ```

Результат тот же.

**Comment by dgdagadin87** [comment]
> werf запускается не в контейнере и проблема не уходит при повторном запуске, так?

Ну да, я просто открываю терминал и выполняю команду

**Comment by dgdagadin87** [comment]
Запустил команду с параметром --introspect-before-error, открылась командная строка, папка shell есть но она пустая

**Comment by dgdagadin87** [comment]
Обновил верфь до версии 1.1.0.beta.3 для линукс. Проблема та же.

**Comment by alexey-igrychev** [comment]
должна примонтироваться директория с host системы со сгенерированным скриптом, но ...

> (1) можно начать с простого теста монтирования
```
tmp_dir=$(mktemp -d)
date > $tmp_dir/date
docker run -v $tmp_dir:/test alpine sh -c "cat /test/date"
```

> (2) убедиться, что werf создаёт этот файл в tmp директории
```
$ tree /tmp/werf-project-data-092709311                                    
/home/aigrychev/werf_tmp/werf-project-data-092709311
└── vxebojl6xk
    └── image
        └── shell-Install
            └── script.sh
```

> (3) обновить docker (странно, что у вас локально версия сервера отличается от клиента)

**Comment by dgdagadin87** [comment]
Результат выполнения (1)
<pre>Unable to find image &apos;alpine:latest&apos; locally
latest: Pulling from library/alpine
c9b1b535fdd9: Pull complete 
Digest: sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d
Status: Downloaded newer image for alpine:latest
cat: can&apos;t open &apos;/test/date&apos;: No such file or directory</pre>

**Comment by alexey-igrychev** [comment]
значит не монтируется хост директория в контейнер
у нас такого прецедента не было, поэтому сложно подсказать в каком направлении копать
думаю, проще всего начать с полной переустановки docker

**Comment by distorhead** [comment]
@dgdagadin87 Приветствую, вопрос еще актуален?
