### ISSUE TITLE
[dockerfile, 1.1] The context files checksum does not count ignored files (.gitignore)

### ISSUE THREAD

**Issue by roman-geraskin** [flant/werf#2315]
Hello. 

Simple synthetic Dockerfile for Dockerfile Image build:
```
FROM alpine

WORKDIR /root/

ADD .config.tar ./
```

werf.yaml:
```
project: test
configVersion: 1
---
image: ~
dockerfile: Dockerfile
```

Running `werf build` starts actual build process only at first time:
```
type multiwerf && . $(multiwerf use 1.1 ea --as-file)
# this will trigger build process
echo date >> config && tar --exclude=./.* -cf .config.tar . && werf build --stages-storage :local
# this will not trigger build process, image from cache will be used
echo date >> config && tar --exclude=./.* -cf .config.tar . && werf build --stages-storage :local
```
So `.config.tar` changes every time but werf ignores it.

BTW: tar-hack is usual vanilla docker build workaround to exclude some files/dirs from image. Because of lack of [COPY exclusion ability](https://github.com/moby/moby/issues/15771).

Running `werf build` with werf 1.0 stable triggers build on each request:
```
type multiwerf && . $(multiwerf use 1.0 stable --as-file)
# this will trigger build process
echo date >> config && tar --exclude=./.* -cf .config.tar . && werf build --stages-storage :local
# this will trigger build process also
echo date >> config && tar --exclude=./.* -cf .config.tar . && werf build --stages-storage :local
```

Werf Version: v1.1.4
You could reproduce described werf build behavior using [this project](https://github.com/roman-geraskin/werf-build-trouble.git)

**Comment by alexey-igrychev** [comment]
Currently, werf uses git ls-tree and git status to calculate a context files checksum for dockerfile image. The algorithm filter is based on globs in `.gitignore` and `.dockerignore` files.

We should implement an extra step to add files that are:
* not covered by `.dockerignore` globs and 
* covered by `.gitignore` globs.

Workaround: remove `.gitignore` file before running werf in CI-job.
Estimate: this week.

Thanks for your attention and feedback.
