### ISSUE TITLE
docker.ENTRYPOINT in shell form doesn't work with docker.CMD

### ISSUE THREAD

**Issue by ilya-lesikov** [flant/werf#2341]
I believe docker.ENTRYPOINT in shell form doesn't properly escape spaces (and maybe other special symbols) in resulting example string: `sh -c echo test1 test2`

Steps to reproduce:
```bash
$ cat > werf.yaml <<EOF
project: test
configVersion: 1
---
image: test
from: alpine
docker:
  ENTRYPOINT: echo
  CMD: ["test1", "test2"]
EOF
$ werf build
$ docker run --rm werf-stages-storage/test:$TAG_OF_BUILT_STAGE
# echo nothing
$ sed -i 's/echo/["echo"]/' werf.yaml
$ werf build
$ docker run --rm werf-stages-storage/test:$TAG_OF_BUILT_STAGE
test1 test2   # works when docker.ENTRYPOINT in exec form
```

Tested on `werf v1.1.9+fix2`

Related #1680

**Comment by alexey-igrychev** [comment]
werf behavior is similar to [docker’s ](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact#understand-how-cmd-and-entrypoint-interact
)(https://prnt.sc/rzyjqt)

### ENTRYPOINT: echo
```
$ cat werf.yaml
project: test
configVersion: 1
---
image: test
from: alpine
docker:
  ENTRYPOINT: echo
  CMD: ["test1", "test2"]

$ docker inspect 4875326acdcd --format="entrypoint: {{ .Config.Entrypoint }} cmd: {{ .Config.Cmd }}"
entrypoint: [/bin/sh -c echo] cmd: [test1 test2]

$ docker run --rm 4875326acdcd # /bin/sh -c echo
```

### ENTRYPOINT: ["echo"]
```
$ cat werf.yaml
project: test
configVersion: 1
---
image: test
from: alpine
docker:
  ENTRYPOINT: ["echo"]
  CMD: ["test1", "test2"]

$ docker inspect 4e3039c626cc --format="entrypoint: {{ .Config.Entrypoint }} cmd: {{ .Config.Cmd }}"
entrypoint: [echo] cmd: [test1 test2]

$ docker run --rm 4e3039c626cc # echo test1 test2
test1 test2
```

**Comment by ilya-lesikov** [comment]
Wow, that's stupid, Docker docs indicate just that:

> The shell form prevents any CMD or run command line arguments from being used

Would be nice to indicate that the exec form can be used at all and would be specified here by default:
https://github.com/flant/werf/blob/7dadcf3f0f7b0360994fa79092a51b400156c868/docs/_data/stages.yml#L285-L286

**Comment by alexey-igrychev** [comment]
I agree with you it is ambiguous behavior.
However, this is [the logic of interaction between ENTRYPOINT and CMD instructions](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact#understand-how-cmd-and-entrypoint-interact) in Docker and werf just repeat that.

**Comment by ilya-lesikov** [comment]
The issue is just your docs show entrypoint and cmd used together in shell form, which doesn't work. Also, in Docker docs it is explicitly specified that the exec form is preffered and they have no (working) examples with both entrypoint and cmd in shell form.

**Comment by alexey-igrychev** [comment]
Thanks for feedback, we'll add notes in comments soon 👌🏼
