### ISSUE TITLE
Add option to specify main config file

### ISSUE THREAD

**Issue by borgius** [flant/werf#2380]
Some times we need to have multiple werf.yaml files in our project (for example, if you want to restructure project, but don't want to change current build process)

`--dir` - specified the main folder with app (and werf.yaml), but if we want to have a different `werf.yaml` for the same folder - we have no options 😞 

Will be great if we can add `--config=<path to werf.yaml>` with allow us to split app folder (--dir) and config file

**Comment by alexey-igrychev** [comment]
Thanks for the feedback.
We will add the option this week and notify you here.
What do you think about a similar option for `.helm` directory?

**Comment by borgius** [comment]
Thank you for the fast reply! 
Yes, it's will be great, if we will have a similar option for helm.

**Comment by borgius** [comment]
Also, if it is possible, will be great if we also can specify path for the `.werf` folder
`--dir-templates=.werf`

**Comment by distorhead** [comment]
Options `--config=werf.yaml`, `--config-templates-dir=.werf` and `--helm-chart-dir=.helm` are available in the v1.1 alpha channel since version https://github.com/flant/werf/releases/tag/v1.1.11.
