### ISSUE TITLE
Access to GitLab CI variables in build-time container

### ISSUE THREAD

**Issue by am813nt** [flant/werf#2385]
Suppose we've got variables defined at build stage in .gitlab-ci,yml:
```
stage: build
...
script:
...
  - werf build-and-publish ...
...
variables:
  TEST=test
```
Is there any way to access them in build-time image i.e. be able to do something like that in werf.yaml?
```
...
shell:
...
  beforeInstall:
    - export TEST=${TEST}  
...
```
These variables may contain sensitive information which is required at build-time (e.g. to hardcode credentials in js apps) and we can't see any documented way to pass them.

**Comment by alexey-igrychev** [comment]
https://werf.io/documentation/configuration/introduction.html#sprig-functions
