### ISSUE TITLE
go templates evolution into "dapp template language"

### ISSUE THREAD

**Issue by diafour** [flant/werf#640]
Go templates are implemented in Helm and Prometheus. I think we can bring best solutions from these projects into dapp.

For example, Helm template language has `$` variable which always returns root context https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/variables.md.
Prometheus has function `args` for passing multiple values into template https://prometheus.io/docs/prometheus/latest/configuration/template_reference/#others.

**Comment by distorhead** [comment]
The werf.yaml config will be revised in the separate issue.
