### ISSUE TITLE
Better messages about stages: add dimg and artifact names

### ISSUE THREAD

**Issue by diafour** [flant/werf#665]
dimg or artifact name is printed at the beggining of build log. Stages or commands can be verbose and in case of error user see only this:

```
verbose output from commands
>>END STREAM
```

Another case is command that print messages and then hanging. User needs to scroll up to know which dimg or artifact cause troubles.

It will be better if message about starting stage will contains dimg or artifact name. Something like this

```
  Install group
    Install [test-app]                                                                       [BUILDING]
Mon Apr 23 09:11:47 UTC 2018
      Launched command: `date && mkdir /app && echo Start > /app1/start.sh`
    Install                                                                                    [FAILED] 1.28 sec
```

or like this

```
  Install group
    Install                                                                                  [BUILDING]
      dimg: test-app
Mon Apr 23 09:11:47 UTC 2018
      Launched command: `date && mkdir /app && echo Start > /app1/start.sh`
    Install                                                                                    [FAILED] 1.28 sec
```

**Comment by diafour** [comment]
More issues about messages: #392

**Comment by alexey-igrychev** [comment]
`<dimg name>: <stage name>`:
* `app: before_install_artifact`;
* or just `before_install_artifact` for nameless dimg.

and also reject messages like `Install group` and `Setup group`
