### ISSUE TITLE
Remote git repo username does not match previous request при указании протокола

### ISSUE THREAD

**Issue by kobel169** [flant/werf#849]
/bug

Если в remote git artifact указать url вида 
`ssh://random@server.example:2222/repo.git`
То сборка падает с ошибкой 

Remote git repo `ssh://random@server.example:2222/repo.git`: `username does not match previous request`!

Судя по всему это связано с функцией на https://github.com/flant/dapp/blob/master/lib/dapp/dimg/git_repo/remote.rb#L43 в которой не ожидается более одного двоеточия. 

В случае использования специфических репозиториев, просто опустить `ssh://` не помогает, сборка зависает на этом этапе. Работа через shell с подобными репозиториями  также требует указания протокола.

**Comment by alexey-igrychev** [comment]
протокол указывать не нужно: `[user@]host:path/to/repo.git`.
зависает обычно, если не получается найти ssh пользователя (специфика rugged).
можно ещё использовать https формат: `https://username@host/path/to/repo.git`

**Comment by alexey-igrychev** [comment]
стоит ещё попробовать опцию [--ssh-key](https://flant.github.io/dapp/dimg_build.html#ssh-key-ssh_key)

**Comment by kobel169** [comment]
В дополнение скажу, что ручная правка гема локально и указание правильного логина для входа при указании протокола ssh:// приводит к корректной работоспособности
